const countryData = {
    // Geoguessr Länder (inQuiz: true)
    "AL": { name: "Albania", domain: ".al", inQuiz: true },
    "AD": { name: "Andorra", domain: ".ad", inQuiz: true },
    "AR": { name: "Argentina", domain: ".ar", inQuiz: true },
    "AU": { name: "Australia", domain: ".au", inQuiz: true },
    "AT": { name: "Austria", domain: ".at", inQuiz: true },
    "BD": { name: "Bangladesh", domain: ".bd", inQuiz: true },
    "BE": { name: "Belgium", domain: ".be", inQuiz: true },
    "BT": { name: "Bhutan", domain: ".bt", inQuiz: true },
    "BO": { name: "Bolivia", domain: ".bo", inQuiz: true },
    "BW": { name: "Botswana", domain: ".bw", inQuiz: true },
    "BR": { name: "Brazil", domain: ".br", inQuiz: true },
    "BG": { name: "Bulgaria", domain: ".bg", inQuiz: true },
    "KH": { name: "Cambodia", domain: ".kh", inQuiz: true },
    "CA": { name: "Canada", domain: ".ca", inQuiz: true },
    "CL": { name: "Chile", domain: ".cl", inQuiz: true },
    "CN": { name: "China", inQuiz: true, domain: ".cn" },
    "CO": { name: "Colombia", domain: ".co", inQuiz: true },
    "HR": { name: "Croatia", domain: ".hr", inQuiz: true },
    "CZ": { name: "Czechia", domain: ".cz", inQuiz: true },
    "DK": { name: "Denmark", domain: ".dk", inQuiz: true },
    "DO": { name: "Dominican Republic", domain: ".do", inQuiz: true },
    "EC": { name: "Ecuador", domain: ".ec", inQuiz: true },
    "EG": { name: "Egypt", inQuiz: true, domain: ".eg" },
    "EE": { name: "Estonia", domain: ".ee", inQuiz: true },
    "SZ": { name: "Eswatini", domain: ".sz", inQuiz: true },
    "FO": { name: "Faroe Islands", domain: ".fo", inQuiz: true },
    "FI": { name: "Finland", domain: ".fi", inQuiz: true },
    "FR": { name: "France", domain: ".fr", inQuiz: true },
    "DE": { name: "Germany", domain: ".de", inQuiz: true },
    "GH": { name: "Ghana", domain: ".gh", inQuiz: true },
    "GR": { name: "Greece", domain: ".gr", inQuiz: true },
    "GL": { name: "Greenland", domain: ".gl", inQuiz: true },
    "GT": { name: "Guatemala", domain: ".gt", inQuiz: true },
    "HU": { name: "Hungary", domain: ".hu", inQuiz: true },
    "IS": { name: "Iceland", domain: ".is", inQuiz: true },
    "IN": { name: "India", domain: ".in", inQuiz: true },
    "ID": { name: "Indonesia", domain: ".id", inQuiz: true },
    "IE": { name: "Ireland", domain: ".ie", inQuiz: true },
    "IL": { name: "Israel", domain: ".il", inQuiz: true },
    "IT": { name: "Italy", domain: ".it", inQuiz: true },
    "JP": { name: "Japan", domain: ".jp", inQuiz: true },
    "JO": { name: "Jordan", domain: ".jo", inQuiz: true },
    "KE": { name: "Kenya", domain: ".ke", inQuiz: true },
    "KG": { name: "Kyrgyzstan", domain: ".kg", inQuiz: true },
    "LA": { name: "Laos", domain: ".la", inQuiz: true },
    "LV": { name: "Latvia", domain: ".lv", inQuiz: true },
    "LS": { name: "Lesotho", domain: ".ls", inQuiz: true },
    "LT": { name: "Lithuania", domain: ".lt", inQuiz: true },
    "LU": { name: "Luxembourg", domain: ".lu", inQuiz: true },
    "MY": { name: "Malaysia", domain: ".my", inQuiz: true },
    "MX": { name: "Mexico", domain: ".mx", inQuiz: true },
    "MN": { name: "Mongolia", domain: ".mn", inQuiz: true },
    "ME": { name: "Montenegro", domain: ".me", inQuiz: true },
    "NL": { name: "Netherlands", domain: ".nl", inQuiz: true },
    "NP": { name: "Nepal", domain: ".np", inQuiz: true },
    "NZ": { name: "New Zealand", domain: ".nz", inQuiz: true },
    "NG": { name: "Nigeria", domain: ".ng", inQuiz: true },
    "MK": { name: "North Macedonia", domain: ".mk", inQuiz: true },
    "NO": { name: "Norway", domain: ".no", inQuiz: true },
    "PK": { name: "Pakistan", domain: ".pk", inQuiz: true },
    "PS": { name: "Palestine", domain: ".ps", inQuiz: true },
    "PA": { name: "Panama", domain: ".pa", inQuiz: true },
    "PE": { name: "Peru", domain: ".pe", inQuiz: true },
    "PH": { name: "Philippines", domain: ".ph", inQuiz: true },
    "PL": { name: "Poland", domain: ".pl", inQuiz: true },
    "PT": { name: "Portugal", domain: ".pt", inQuiz: true },
    "PR": { name: "Puerto Rico", domain: ".pr", inQuiz: true },
    "RE": { name: "Réunion", domain: ".re", inQuiz: true },
    "RO": { name: "Romania", domain: ".ro", inQuiz: true },
    "RU": { name: "Russia", domain: ".ru", inQuiz: true },
    "RW": { name: "Rwanda", domain: ".rw", inQuiz: true },
    "SN": { name: "Senegal", domain: ".sn", inQuiz: true },
    "RS": { name: "Serbia", domain: ".rs", inQuiz: true },
    "SG": { name: "Singapore", domain: ".sg", inQuiz: true },
    "SK": { name: "Slovakia", domain: ".sk", inQuiz: true },
    "SI": { name: "Slovenia", domain: ".si", inQuiz: true },
    "ZA": { name: "South Africa", domain: ".za", inQuiz: true },
    "KR": { name: "South Korea", domain: ".kr", inQuiz: true },
    "ES": { name: "Spain", domain: ".es", inQuiz: true },
    "LK": { name: "Sri Lanka", domain: ".lk", inQuiz: true },
    "SE": { name: "Sweden", domain: ".se", inQuiz: true },
    "CH": { name: "Switzerland", domain: ".ch", inQuiz: true },
    "TW": { name: "Taiwan", domain: ".tw", inQuiz: true },
    "TH": { name: "Thailand", domain: ".th", inQuiz: true },
    "TR": { name: "Turkey", domain: ".tr", inQuiz: true },
    "UG": { name: "Uganda", domain: ".ug", inQuiz: true },
    "UA": { name: "Ukraine", domain: ".ua", inQuiz: true },
    "AE": { name: "United Arab Emirates", domain: ".ae", inQuiz: true },
    "GB": { name: "United Kingdom", domain: ".uk", inQuiz: true },
    "US": { name: "United States", domain: ".us", inQuiz: true },
    "UY": { name: "Uruguay", domain: ".uy", inQuiz: true },
    "VN": { name: "Vietnam", inQuiz: true, domain: ".vn" },

    // Länder ohne Streetview
    "AF": { name: "Afghanistan", domain: ".af", inQuiz: false },
    "DZ": { name: "Algeria", domain: ".dz", inQuiz: false },
    "AO": { name: "Angola", domain: ".ao", inQuiz: false },
    "BA": { name: "Bosnia and Herzegovina", domain: ".ba", inQuiz: false },
    "BM": { name: "Bermuda", domain: ".bm", inQuiz: false },
    "CY": { name: "Cyprus", domain: ".cy", inQuiz: false },
    "SV": { name: "El Salvador", domain: ".sv", inQuiz: false },
    "HK": { name: "Hong Kong", domain: ".hk", inQuiz: false },
    "IR": { name: "Iran", inQuiz: false, domain: ".ir" },
    "MD": { name: "Moldova", domain: ".md", inQuiz: false },
    "MC": { name: "Monaco", domain: ".mc", inQuiz: false },
    "MP": { name: "Northern Mariana Islands", domain: ".mp", inQuiz: false },
    "SM": { name: "San Marino", domain: ".sm", inQuiz: false },
    "SA": { name: "Saudi Arabia", inQuiz: false, domain: ".sa" },
    "CR": { name: "Costa Rica", domain: ".cr", inQuiz: false },
};
